language: python
python:
  - "3.7.1"
  - "3.8"
install:
  - pip3 install .
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install pylint
  - pip3 install pytest
script:
  - python -m pytest -v test/
  - coverage run --source ./server/ -m pytest -v ./test/
  - pylint server/
env:
  - CODECOV_TOKEN='7a65f4b9-4704-4281-ad3b-e4cc37bae9c7'
after_success:
  - bash <(curl -s https://codecov.io/bash)
